### ISSUE TITLE
Create a simple register form

### ISSUE THREAD

**Issue by nghianguyentek** [nghianguyentek/server#10]
A form with:
- email as username: `usn`
- password: `pw`
- re-password
- csrf token (optional): `csrfTk`
- one submit button

Display form URL: `GET /register`

Submit:
- Protocol: https
- URL: `POST /v1/accounts`
- Content-Type: `application/json`
- Sample: `{ usn: 'abc@gmail.com', pw: '12345678', csrfTk: 'xyz'  }`

**Comment by quynhlinh137** [comment]
Why is this task assigned to you?
