### ISSUE TITLE
Decide header templates

### ISSUE THREAD

**Issue by nghianguyentek** [nghianguyentek/server#4]
Considered aspects:
- Mobile first
- When:
  - Not login yet
  - Logged in

**Comment by quynhlinh137** [comment]
![image](https://user-images.githubusercontent.com/79017242/230724051-db82b789-4fa2-4e64-8df8-d7c90af368ce.png)

**Comment by quynhlinh137** [comment]
tui nghĩ là search nên để ở dưới, vì như ông nói, nó tiện cho ng dùng hơn. 
Cái header có khi nó ở đó luôn, nhưng nhiều khi lướt qua trang đầu thì nó sẽ cuộn lên. Tui thì prefer là cố định luôn để dễ thấy, cá nhân tui mỗi lần cần lại phải lướt ngược lên đầu thấy khá bất tiện.
Deploy thì như 1 html element bình thường, có vị trí cố định.

**Comment by nghianguyentek** [comment]
> 1. tui nghĩ là search nên để ở dưới, vì như ông nói, nó tiện cho ng dùng hơn. 
Why?

>  Tui thì prefer là cố định luôn
OK. Actually, it's always there.

> Deploy thì như 1 html element bình thường
HTML is not only to represent data, it also provides semantics. Indeed, there are `header`, `list`, etc. 

> You didn't mention the differences between before and after a user logs in

**Comment by nghianguyentek** [comment]
@quynhlinh137 Any progress?

**Comment by quynhlinh137** [comment]
![image](https://user-images.githubusercontent.com/79017242/236535652-6b0181ca-4d2e-4fda-9153-e8aa5155341c.png)
