### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by nghianguyentek** [nghianguyentek/server#6]
- Learning how to create SVG image at https://www.w3schools.com/graphics/svg_intro.asp
- Create logos for kihonvn and shoshin

Basic knowledge about logo
|Type|Description|Sample|Advantage|Disadvantage
|:-:|-|-|-|-|
|Wordmark|Brand name|Google, Facebook, Coca cola, etc.|Best for new brand|Longer name
|Lettermark|Brand name acronym|HBO, IBM, NASA, etc.|Short|Hard to understand for new brand
|Pictorial|Shape related to brand name|Apple, Twitter, etc.|Easy to remember|Hard to understand for new brand
|Abstract|Shape unrelated to brand name|Car logos, Pepsi, Adidas, Nike, etc.|Unique|Hard to understand for new brand and difficult to create
|Mascots|Cartoon symbol|KFC|Children friendly|Not attractive with others
|Combination|Combine related text and symbols|Beer logos|Having advantages of used types|None
|Emblem|Texts inside shapes or symbols|Starbucks, Harley Division, etc.|Same as Combination|May difficult to read

**Comment by quynhlinh137** [comment]
Done item (1).
For item (2), could you give the designs?

**Comment by quynhlinh137** [comment]
Shoshin 
![image](https://user-images.githubusercontent.com/79017242/232115139-c5ca4c87-25eb-41b2-96bd-5033750fef77.png)

is it too simple?

**Comment by quynhlinh137** [comment]
Shoshin
![image](https://user-images.githubusercontent.com/79017242/232117304-e2364b71-007d-4988-9d2b-24c6ca408de3.png)

**Comment by quynhlinh137** [comment]
![image](https://user-images.githubusercontent.com/79017242/232123619-fabb27ab-bffc-427c-93c4-925d34e3606b.png)

**Comment by quynhlinh137** [comment]
![image](https://user-images.githubusercontent.com/79017242/232123979-bb92b162-e869-4f96-b82f-3b0e4ace5521.png)

**Comment by quynhlinh137** [comment]
shoshin. 
![image](https://user-images.githubusercontent.com/79017242/232201286-2f592b9b-9760-422b-8177-466a5ae720dc.png)
Mà ko biết vẽ.

**Comment by nghianguyentek** [comment]
@quynhlinh137 how about this ticket?
