### ISSUE TITLE
Design and create `accounts` table

### ISSUE THREAD

**Issue by nghianguyentek** [nghianguyentek/server#8]
Create a MySQL SQL script to create `accounts` table that contains user credential for basic authentication:
- *id*: INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
- *username* (`usn`): VARCHAR(64) NOT NULL UNIQUE
- *password* (`pw`): VARCHAR(32) NOT NULL
- *status* (`st`): TINYINT NOT NULL DEFAULT 0

Status can be:
- `0`: Inactive
- `1`: Active

**References**:
- https://www.w3schools.com/mysql/mysql_create_table.asp
- https://dev.mysql.com/doc/refman/8.0/en/create-table.html
- https://dev.mysql.com/doc/refman/8.0/en/data-types.html
- https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
- https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
- https://dev.mysql.com/doc/refman/8.0/en/char.html
- https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html
- https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html
- https://www.w3schools.com/sql/sql_primarykey.ASP
- https://www.w3schools.com/mysql/mysql_unique.asp
- https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

**Comment by nghianguyentek** [comment]
> Status: dùng BIT(1) cũng đc?
It depends on how many states an account has.

> Id: nếu thêm NOT NULL thì có gì khác? Các ví dụ trong w3s và sql thì thấy đều có NOT NULL
Reread Primary Key constraint

> Có nên bổ sung: email VARCHAR (32) phoneNo VARCHAR (16)
We don't use these for authentication. They may be in profile/contact information table.

**Comment by quynhlinh137** [comment]
Status: dùng BIT(1) cũng đc?
It depends on how many states an account has.
As you said, there only 2 statuses : 0 & 1.

**Comment by nghianguyentek** [comment]
> As you said, there’re only 2 statuses : 0 & 1.
Think about the possibilities in the future.
