### ISSUE TITLE
Design and create `userAgents` table

### ISSUE THREAD

**Issue by nghianguyentek** [nghianguyentek/server#9]
This table contains client application (often a browser) information that users used to access system.
Based on the `user-agent` header in HTTP Request, try to design the table

Samples:
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0`: Firefox v102.0 MacBook
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15` Safari v15.5 MacBook
- `curl/7.79.1`: curl macOS

Columns
- `id`: BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
- `t` (type): TINYINT UNSIGNED DEFAULT 1
- `n` (name): TINYINT UNSIGNED
- `vs` (version): VARCHAR(16)  
- `sT` (subType): TINYINT UNSIGNED
- `os`: TINYINT UNSIGNED
- `osVs` (OS version): VARCHAR(8)

Type values:
- `0`: Unidentified
- `1`: Browser
- `2`: Java
- `3`: Node.js
- `4`: curl

Name values:
- `0`: Unidentified
- `1`: Google Chrome
- `2`: Safari
- `3`: Firefox
- `4`: MS Edge
- `5`: Opera

Sub-type values
- `0`: Unidentified
- `1`: Mobile
- `2`: Desktop

OS values:
- `0`: Unidentified
- `1`: Windows
- `2`: macOS
- `3`: Linux
- `4`: iOS
- `5`: Android

**Comment by quynhlinh137** [comment]
What is the purpose of this table? Is it a kind/information of cookies? 
How to know a user agent is an old or new one? Is it possible that there are 2 user-agents whose all characters, except for id, are the same?

**Comment by nghianguyentek** [comment]
What is the purpose of this table? Is it a kind/information of cookies?
> Statistics, reports, etc. For example, 75% IPhone users use Chrome instead of Safari.
How to know a user agent is an old or new one? 
> We don't care this
Is it possible that there are 2 user-agents whose all characters, except for id, are the same?
> There is no id here. Two or many users can use the same user agent.

**Comment by quynhlinh137** [comment]
> There is no id here. Two or many users can use the same user agent.

You did mention id in the table? The 1st column.

**Comment by quynhlinh137** [comment]
A syntax correction is commited on branch #9.
